Update unlighthouse.yml

diff --git a/.github/workflows/unlighthouse.yml b/.github/workflows/unlighthouse.yml
--- a/.github/workflows/unlighthouse.yml
+++ b/.github/workflows/unlighthouse.yml
@@ -18,7 +18,7 @@ jobs:
         run: mkdir -p $GITHUB_WORKSPACE/unlighthouse/dist
 
       - name: Run Unlighthouse with Debug
-        run: unlighthouse-ci --site http://51.44.25.104/en --build-static --output-path $GITHUB_WORKSPACE/unlighthouse/dist || echo "Unlighthouse failed"
+        run: unlighthouse-ci --site http://51.44.25.104/en --output-path $GITHUB_WORKSPACE/unlighthouse/dist || echo "Unlighthouse failed"
 
       - name: Debug Workspace
         run: ls -R $GITHUB_WORKSPACE
